name: Probe inputs
on:
  workflow_dispatch:
    inputs:
      version:
        description: "ver"
        required: false
        type: string
        default: ""
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo pong
